### ISSUE TITLE
hjson file with long string value in it freezes visual studio code on add node

### ISSUE THREAD

**Issue by dreadjr** [hjson/vscode-hjson#4]
1. disable all extensions except hjson
2. rename attached file to `.hjson` extension
3. open file in vscode
4. goto top of file and start typing `o: {},` to add another node

Vscode freezes...

[test.hjson.txt](https://github.com/hjson/vscode-hjson/files/1738509/test.hjson.txt)

**Comment by ALIENQuake** [comment]
@dreadjr can't reproduce, safe to close?

**Comment by dqsully** [comment]
No, I can reproduce it

Start with that test.hjson.txt file, and then type the `o: {},` here:
```hjson
{o: {}
  key: '--- (etc.)'
}
```

I'll take a look at the root cause. Thanks for reporting this @dreadjr.

**Comment by ALIENQuake** [comment]
@dqsully Indeed this bug still exist.

**Comment by dqsully** [comment]
So far I've learned that ~this doesn't happen in Atom~, and that it has something to do with the number of `\n` escapes in the string and any of `,}#/` occurring immediately after the string. If there is whitespace in-between the end of the string and those characters though, it works properly.

Edit: it does happen in Atom when using just `\n`. It's just that Atom doesn't parse very far through a long line.
