### ISSUE TITLE
Syntax highlighting does not recognize comments in front of keys

### ISSUE THREAD

**Issue by geekley** [hjson/vscode-hjson#5]
Unlike https://hjson.org/try the editor in vscode doesn't recognize comments in front of keys, in the same line.
For example:
```
# https://hjson.org/try
{
key1:
// ok
  'Value' # ok

key2:
# ok
  "Value" // ok

key3: #breaks syntax
  Value

key4: //breaks syntax
  '''
  Multi.
  Line.
  '''

key5: Broken
}
```

**Comment by laktak** [comment]
Sorry, this project is EOL, see https://hjson.org

**Comment by dqsully** [comment]
This should be fixed in the next release of this package. Thank you for reporting this @geekley
