### ISSUE TITLE
No syntax if top-level braces are not present

### ISSUE THREAD

**Issue by ALIENQuake** [hjson/vscode-hjson#6]
No syntax if there is not top-level braces:

![](https://image.prntscr.com/image/7NwbrotpQ2uSntuHCVJqpw.png)

**Comment by laktak** [comment]
Sorry, this project is EOL, see https://hjson.org

**Comment by dqsully** [comment]
This syntax is [deprecated](http://hjson.org/syntax.html#root-braces-obsolete) and it would be really hard to implement properly in VS Code and other TextMate-based editors, so I don't plan on supporting it.
