### ISSUE TITLE
Freeze with large file on open.

### ISSUE THREAD

**Issue by SemperFu** [hjson/vscode-hjson#7]
We have a decent sized hjson file (3994) lines. When the plugin is enabled VS Code hangs trying to open it and it has to be closed. Disabled isn't an issue to open it up.
I have attached the file as well

[menu.txt](https://github.com/hjson/vscode-hjson/files/2602396/menu.txt)

**Comment by dqsully** [comment]
This should be fixed in the next release of vscode-hjson, and it's already fixed in Atom. Thanks for reporting this.
