### ISSUE TITLE
File explorer icon

### ISSUE THREAD

**Issue by leosdad** [hjson/vscode-hjson#8]
Hi, it would be great if the extension also changed the default "text" icon to something more meaningful like the JSON icon. Thanks!

**Comment by dqsully** [comment]
I believe this is up to the icon package authors. With Material Icons you can define your own language-to-icon associations like so:

VSCode's global `settings.json`:
```json
{
    "material-icon-theme.languages.associations": {
        "hjson": "json"
    }
}

**Comment by leosdad** [comment]
Thanks, it does work with Material Icons. I thought there would be a way to embed the custom icon in the extension. Cheers
